# Generated by Django 3.1.3 on 2020-12-16 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='Job Title')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=300, verbose_name='Job Title')),
                ('min_requirements', models.CharField(max_length=300, verbose_name='Minimum Requirements')),
                ('recommend_requirements', models.CharField(max_length=300, verbose_name='Recommended Requirements')),
                ('salary', models.IntegerField(verbose_name='Salary')),
                ('offer_end_date', models.DateField(verbose_name='Offer End Date')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company')),
                ('company_info', models.CharField(max_length=300, verbose_name='Company Info')),
                ('applicants', models.ManyToManyField(to='accounts.Employee')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employer')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.keyword')),
            ],
        ),
    ]
